### ISSUE TITLE
Values are multiplied by 100 after save

### ISSUE THREAD

**Issue by MatteoJoliveau** [z-productions/administrate-field-money#2]
When writing an amount in an input field (e.g., `22.30`) and saving, the actual value saved is not transposed in cents and is therefore multiplied by 100.

Input:
![image](https://user-images.githubusercontent.com/9077612/41612645-d0e8e172-73f3-11e8-8f9f-0935737227dd.png)

Result:
![image](https://user-images.githubusercontent.com/9077612/41612661-db439446-73f3-11e8-8497-ecf44cd87c03.png)

Rails 5.2.0
Administrate 0.10.0
administrate-field-money 0.1.0
money-rails 1.11.0

**Comment by michelegera** [comment]
Ciao @MatteoJoliveau, thanks for reporting this! 😄

I have an application with the same set of dependencies but I wasn’t able to reproduce the bug. As a matter of fact, if I apply the changes you submitted in #3, I get wrong amounts (e.g. inputting €22.30 and saving gets me €0.22).

Can you please check the JS console and see if it throws any errors? And can you double-check in the Rails console to make sure that the amount saved is actually in cents? Also, which options are you calling the field with, in the dashboard (i.e. `Field::Money.with_options({…})`)?

**Comment by jondkinney** [comment]
@MatteoJoliveau are you storing the retail price as a decimal in your database? If so, that's your issue. The money gem assumes (requires, actually) the price column is an integer. Just found this out myself (the hard way :)

**Comment by MatteoJoliveau** [comment]
Hi @michelegera and @jondkinney, values are correctly stored as integers in Postgres and Money-Rails is able to parse them correctly.
![image](https://user-images.githubusercontent.com/9077612/44330318-fe028e80-a466-11e8-9f65-4bca921a4d80.png)

No errors at all in the browser console.

**Comment by MatteoJoliveau** [comment]
Also this is my field configuration.

```ruby
Field::Money.with_options(
  code: 'EUR',
  symbol: '€',
  delimiter: '.',
  separator: ','
)
```

**Comment by pkonovalov** [comment]
Have exactly same dependencies and same problem. Checked in console after saving product price "3.22" in administrate:
```
Product.find(9).price_eur
  Product Load (0.6ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 9], ["LIMIT", 1]]
=> #<Money fractional:32200 currency:EUR>

Product.find(9).price_eur.currency
  Product Load (0.5ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 9], ["LIMIT", 1]]
=> #<Money::Currency id: eur, priority: 1, symbol_first: true, thousands_separator: ,, html_entity: , decimal_mark: ., name: Euro, symbol: €, subunit_to_unit: 100, exponent: 2, iso_code: EUR, iso_numeric: , subunit: Cent, smallest_denomination: >
```

**Comment by michelegera** [comment]
Hi @MatteoJoliveau and @pkonovalov,

seems to me that the back-end part is fine and the error might be in the JS that’s parsing the masked `input` field and copying the value in cents to a hidden sibling input (open DevTools and inspect the input field and you’ll see what I mean).

Although I have not been able to reproduce the bug yet, I think I spotted a possible rounding error. Could you please check out [this branch](https://github.com/zooppa/administrate-field-money/tree/fix-amounts), give it a spin in your development environment and see it it fixes the issue?

To try the branch locally just clone the repo, check out the `fix-amounts` branch and edit your app’s Gemfile like this: `gem 'administrate-field-money', path: '../administrate-field-money'`.

Thanks!

**Comment by pkonovalov** [comment]
Finally figured out, that problem was in the attribute which is defined in dashboard. If I define "_cents" attribute - everything works correctly.

Made a test case with two fields:
`price_rub` is defined in dashboard with cents:
```
    price_rub_cents: Field::Money.with_options(...),
```
`price_eur` is defined in dashboard without cents
```
    price_eur: Field::Money.with_options(...),
```

when form is submitted in administrate you can see Form Data which is sent to backend:
```
price_rub_cents: ₽81.50
product_variant[price_rub_cents]: 8150
price_eur: €3.22
product_variant[price_eur]: 322
```
![administrate](https://user-images.githubusercontent.com/729114/46766647-3b5afe00-cceb-11e8-921c-edb61c58b74f.png)

So the value `322` for euro was sent to `price_eur`, not to `price_eur_cents`.

The resolution is to define attributes with `_cents` in dashboard, and it should be fixed in example in Readme.md

**Comment by michelegera** [comment]
Ah, good catch!

I’ve clarified that in the [README](../blob/f91bd218348191f90be7eac49be1c33b12447bf5/README.md) and released [a new version](https://rubygems.org/gems/administrate-field-money/versions/0.1.1).

Thanks guys!
