### ISSUE TITLE
Need to require 'money'

### ISSUE THREAD

**Issue by iamnader** [z-productions/administrate-field-money#4]
'money' isn't required in your lib folder, so if it hasn't already been required somewhere else in the project the templates fail to load

**Comment by michelegera** [comment]
Hey @iamnader, good catch!

I’ve pushed a fix in the [`require-money`](https://github.com/zooppa/administrate-field-money/tree/require-money) branch, can you go ahead and check if it fixes your problem?

You can use it from your project’s Gemfile with:
```
gem 'administrate-field-money', github: 'zooppa/administrate-field-money', branch: 'require-money'
```

Thanks!

**Comment by iamnader** [comment]
That fixed it! Thanks

**Comment by michelegera** [comment]
@iamnader that’s great! I’ve just released a [new version of the gem](https://rubygems.org/gems/administrate-field-money/versions/0.1.2) that incorporates that change 🙌
