### ISSUE TITLE
Most recent changes not deployed to Rubygems

### ISSUE THREAD

**Issue by wkirby** [z-productions/administrate-field-money#7]
Hi there! I see that the work on `master` includes Rails 7 support, but `0.2.1` on [rubygems](https://rubygems.org/gems/administrate-field-money/versions/0.2.1) still requires `rails < 7`. I know this gem isn't actively maintained, but can the current changes on `master` be published as a new version to rubygems?

**Comment by michelegera** [comment]
Hi @wkirby!

Thanks for the nudge — totally my bad. I’ve just released [v0.3.0](https://rubygems.org/gems/administrate-field-money/versions/0.3.0) with the latest updates 😄
